# Generated by Django 5.2.6 on 2025-09-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_remove_artwork_created_at_remove_artwork_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
