# Generated by Django 5.2.6 on 2025-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0003_alter_artwork_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
