# Generated by Django 5.2.6 on 2025-10-01 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_alter_auctionrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_price',
            new_name='reserve_price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='is_active',
        ),
        migrations.AddField(
            model_name='auction',
            name='auction_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artworks.auctionrequest'),
        ),
        migrations.AddField(
            model_name='auction',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artworks.artwork'),
        ),
    ]
