# Generated by Django 5.2.6 on 2025-10-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_rename_starting_price_auction_reserve_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount']},
        ),
    ]
