# Generated by Django 5.2.6 on 2025-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0008_alter_bid_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='sale_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('auction', 'Live Auction')], default='fixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
