# Generated by Django 5.2.6 on 2025-10-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0011_user_location_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default-avatar.png', null=True, upload_to='profile_images/'),
        ),
    ]
