# Generated by Django 5.2.6 on 2025-10-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0012_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionrequest',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
