# Generated by Django 5.2.6 on 2025-10-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0013_auctionrequest_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionrequest',
            name='sold',
        ),
        migrations.AddField(
            model_name='artwork',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
