# Generated by Django 5.2.6 on 2025-10-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0016_paymentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsession',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
