# Generated by Django 5.2.6 on 2025-10-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0018_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
